spec:
  template:
    metadata:
      annotations:
      {{- include "memcached-exporter.sysdigAnnotations" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        {{- if not .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        {{- if .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-ubi"
        {{- end }}        
        ports:
          - containerPort: {{ .Values.port }}
        env:
        {{- if ne .Values.url.name ""}}
        - name: MEMCACHED_ADDR
          value: {{ .Values.url.name }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}