{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-mongodb-exporter.secretName" . }}
  labels:
    {{- include "mongodb-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.existingSecret.key }} : {{ required "A MongoDB URI is required" .Values.mongodb.uri | b64enc }}
{{- end -}}