{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-mongodb-exporter.secretName" . }}
  labels:
    {{- include "mongodb-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.sslmode }}
  {{ .Values.existingSecret.key | nindent 4  }} : {{ required "A MongoDB URI is required" .Values.mongodb.uri | b64enc }} {{ "/admin?ssl=true&sslclientcertificatekeyfile=/etc/mongodb/mongodb-exporter-key.pem&sslinsecure=true&sslcertificateauthorityfile=/etc/mongodb/mongodb-exporter-ca.pem" | b64enc }}
  {{- end -}}
  {{- if .Values.tlsmode }}
  {{ .Values.existingSecret.key | nindent 4  }} : {{ required "A MongoDB URI is required" .Values.mongodb.uri | b64enc }} {{ "/admin?tls=true&tlsCertificateKeyFile=/etc/mongodb/mongodb-exporter-key.pem&tlsAllowInvalidCertificates=true&tlsCAFile=/etc/mongodb/mongodb-exporter-ca.pem" | b64enc }}
  {{- end -}}  
  {{- if and (not .Values.sslmode) (not .Values.tlsmode) -}}
  {{ .Values.existingSecret.key | nindent 4 }} : {{ required "A MongoDB URI is required" .Values.mongodb.uri | b64enc }}
  {{- end -}}
{{- end -}}