apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promcat-postgresql.secretName" . }}
data:
  POSTGRES_EXPORTER_PASSWORD: {{ required "A valid password must be passed in .Values.dbInstance.password" .Values.dbInstance.password | printf "%s" | b64enc | quote }}
  {{- if .Values.dbInstance.sslRootCertEnabled }}
  postgres-ssl-root-cert: |
    {{- required "A valid SSL certificate must be passed in .Values.dbInstance.sslRootCert" .Values.dbInstance.sslRootCert | printf "%s" | b64enc | nindent 4 }}
  {{- end }}